config/routes.rb
UserTweets::Application.routes.draw do
  root :to => "users#index"
  resources :users do
    resources :tweets, :tools
  end

  resources :tweets
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :category
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :tweet, :dependent => :destroy
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_and_belongs_to_many :users
  before_save :check_counts

  CONDITIONS = ["New", "Rusty", "Broken"]

  def toggle_condition
    c_index = CONDITIONS.find_index(self.condition)
    self.condition = CONDITIONS[c_index - 1]
    self.save
  end

  private
  def check_counts
    if counts == 3
      ToolMailer.low_counts(@user).deliver
    end
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :User
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_one :location

  before_save :check_location
  before_save :set_show_location

  after_update {|tweet| logger.info "Tweet #{tweet.id} updated" }
  after_destroy {|tweet| logger.info "Tweet #{tweet.id} deleted" }

  scope :recent,-> {  order('created_at desc').limit(4) }
  scope :about, -> { where(show_location: true, location: {name:'about'}) }

  validates :message, presence: true

  accepts_nested_attributes_for :location

  private

  def check_location
    if self.location
      self.show_location = true
    end
  end

  def set_show_location
    self.show_location = location
  end
end

app/models/user.rb
 class User < ActiveRecord::Base
  has_many :tweets
  has_and_belongs_to_many :tools

  def as_json(options)
    super(options || {only: [:name, :counts], include: :tools})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @tools = @user.tools
  end

  def show
    @user = User.find(params[:user_id])
    @tool = @user.tools.find(params[:id])
    render json: @tool.to_json(except: [:id, :created_at, :updated_at, :email], include: :User)
  end

  def create
    @tool = Tool.new(params[:post])
    if @tool.save
      render json: @tool, status: :created, location: @tool
    else
      render json: @tool.errors, status: :unprocessable_entity
    end
  end

  def fire_Tool
    @tool = Tool.find(params[:id])
    @tool.fire!
    if @tool.low_counts?
      render :fire_and_reload
    end
  end


  def toggle_condition
    @tool = Tool.find(params[:id])
    @tool.toggle_condition
    respond_to do |format|
      format.html { redirect_to @tool, notice: 'Changed condition' }
      format.js
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    if params[:user_id]
      @tweets = Tweet.recent.includes(:location).where(User_id: params[:ser_id])
    else
      @tweets = Tweet.recent.includes(:location)
    end
    @about_tweets = Tweet.recent.about

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  def new
    @user = User.find(params[:user_id])
    @tweet = Tweet.new
    @tweet.location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @user = User.find(params[:user_id])
    location = params[:tweet].delete :location
    @tweet = @user.tweets.new(params[:tweet])
    @tweet.build_location(location)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])
    binding.pry
    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:User])
    @user.save
    respond_with @user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserTweets</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for([@user, @tool]) do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :counts %>
  <%= f.select :condition, ["New", "Old", "The oldest"] %>
  <%= f.date_select :purchased_on %>
<% end %>

app/views/tools/index.html.erb
<h2><%= @user.name %>'s tools</h2>
<ul>
<% @tools.each do |w| %>
  <li><%= link_to w.name, [@user, w] %></li>
<% end %>
</ul>
<%= link_to "New Tool", new_user_Tool_path(@user) %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>
<ul>
  <li>
    <em>Name:</em>
    <%= @tool.name %>
  </li>
  <li>
    <em>Condition:</em>
    <span id="condition"><%= @tool.condition %></span>
    <%= link_to "Toggle", toggle_condition_Tool_path(@tool), remote: true %>
  </li>
  <li>
    <em>counts:</em>
    <span id="counts"><%= @tool.counts %></span>
  </li>
</ul>

app/views/tweets/_form.html.erb
<%= form_for([@user, @tweet]) do |f| %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.fields_for :location do |l| %>
      <%= l.label :name, :location %><br />
      <%= l.text_field :name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Message</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.message %></td>
    <td><%= tweet.User.name %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<% unless params[:user_id] %>
  <p><%= link_to "Back to users", users_path %></p>
<% end %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tweets_path(@user) %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>User:</b>
  <%= @tweet.User.name %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> | <%= link_to 'Delete', tweet_path(@tweet),confirm: 'Are you sure?', method: :delete %>

<p><%= link_to "Back to Tweets", tweets_path %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_tool.html.erb
<%= div_for Tool do %>
  <h2><%= Tool.name %></h2>
  <p>
    Condition: <%= Tool.condition %>
    counts: <%= Tool.counts %>
    Purchased <%= time_ago_in_words Tool.purchased_on %> ago
  </p>
<% end %>

app/views/users/index.html.erb
<h1>users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user %></li>
  <% end %>
</ul>
<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render "form" %>

app/views/users/show.html.erb
<%= render @user.tools %>

<p><%= pluralize(@user.tweets.size, "Tweet") %></p>

<p><%= link_to "Create a new Tweet for #{@user.name}", new_user_tweet_path(@user) %></p>
<p><%= link_to "Back to users", users_path %></p>